[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração específica para a branch LandingPage
[context.LandingPage]
  command = "npm run build"
  publish = "dist"
